### ISSUE TITLE
carbon_yellowstone_grpc_datasource etc not posted to https://docs.rs/

### ISSUE THREAD

**Issue by 0xNaixi** [sevenlabs-hq/carbon#98]
carbon_yellowstone_grpc_datasource etc not posted to https://docs.rs/

https://docs.rs/releases/search?query=carbon&sort=recent-updates

**Comment by KellianDev** [comment]
There are dependency issues with the Yellowstone gRPC crates that require us to be patching crates when using with the Solana SDK crate. It's not possible to publish a crate with dependency patches. So, for now, the recommended approach is to use it as a git dependency like this, with the following patch:

```toml
carbon-yellowstone-grpc-datasource = { version = "0.3.0", git = "https://github.com/sevenlabs-hq/carbon.git" }

[patch.crates-io.curve25519-dalek]
git = "https://github.com/anza-xyz/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"
```
